'use strict';

var base = module.superModule;
var Site = require('dw/system/Site');
var currentSite = Site.getCurrent();

base.screenerIDDesktop = currentSite.getCustomPreferenceValue('eScreenerId');
base.defaultAppID = currentSite.getCustomPreferenceValue('UHCHearing_default_appId');
base.sonarBaseURL = currentSite.getCustomPreferenceValue('hearingtestbaseURL');
base.lifestyleFirstQuestionsID = currentSite.getCustomPreferenceValue('lifestyleFirstQuestionsID');
base.screenerIDMobile = currentSite.getCustomPreferenceValue('screenerIDMobile');
base.recaptchaSiteKey = currentSite.getCustomPreferenceValue('recaptchaSiteKey');
base.allowedFileTypes = currentSite.getCustomPreferenceValue('allowedFiles');
base.allowedFileLength = currentSite.getCustomPreferenceValue('allowedFilelength');
base.googleMapAPIkey = currentSite.getCustomPreferenceValue('mapAPI');
base.micrositeUsersList = currentSite.getCustomPreferenceValue('micrositeUsersList');
base.providerSearchRadius = currentSite.getCustomPreferenceValue('providerSearchRadius');
base.communityLogoutURL = currentSite.getCustomPreferenceValue('communityLogoutURL');
base.resourcesVideoURL = currentSite.getCustomPreferenceValue('resourcesVideoURL');
base.coverageMapping = currentSite.getCustomPreferenceValue('coverageMapping');
base.customerSvcMail = currentSite.getCustomPreferenceValue('customerServiceEmail');
base.oauthProvider = currentSite.getCustomPreferenceValue('oauthProvider');
base.enableTraditionalProduct = currentSite.getCustomPreferenceValue('enableTraditionalProduct');
base.enableRecaptcha = currentSite.getCustomPreferenceValue('recaptchaEnable');
base.enableHeathPlan = currentSite.getCustomPreferenceValue('healthPlanCheckEnable');
base.minPriceRefineValue = currentSite.getCustomPreferenceValue('priceRefinementMinValue');
base.listpricebookId = currentSite.getCustomPreferenceValue('listpricebookId');
base.maxSearchSuggestions = currentSite.getCustomPreferenceValue('maxSearchSuggestions');
base.restrictedBrands = currentSite.getCustomPreferenceValue('restrictedBrands');
base.enableSorting = currentSite.getCustomPreferenceValue('enableSorting');
base.coverageBenefitsDescription = currentSite.getCustomPreferenceValue('coverageBenefitsDescription');
base.otcMaxOrderQty = currentSite.getCustomPreferenceValue('otcMaxOrderQty');
base.pageMetaTitle = currentSite.getCustomPreferenceValue('pageTitle');
base.allowMiddlewareAPIWithSubsID = currentSite.getCustomPreferenceValue('allowMiddlewareAPIWithSubsID');
module.exports = base;
