orbs:
    node: circleci/node@1.1

jobs:
    build:
        working_directory: ~/build_only
        executor:
            name: node/default
            tag: '12.16'
        steps:
            - checkout
            - run: npm install
            - run: npm run lint
version: 2.1
